### PR TITLE
(Feature) Allow specifying custom security group for Load Balancer

### PR DESCRIPTION
**Pull request by Stretch96**

### CODE REVIEW

**Comment by Stretch96** [comment]
Having issues conditionally using the specified security group

**Comment by npalm** [comment]
@Stretch96 sorry for the late response, what is the current status of the PR? I will try to have a look at the issue later today.

**Comment by Stretch96** [comment]
I've not had a chance to look further into this yet, but I was trying to add the ability to specify a security group id, which would then add that to the load balancer, and not create the default one currently in the module.

However, I was hitting a few terraform bugs - https://github.com/hashicorp/terraform/issues/10857

**Comment by Stretch96** [comment]
@npalm This one's ready for review now 👍 

Instead of trying to allow the original security group to be overwritten, I've added in the ability to specify extra security groups using `var.lb_security_group_ids`

**Comment by npalm** [comment]
@Stretch96 sorry for some reason I missed you message. Thanks for the PR.

**Pull request merged**
